### ISSUE TITLE
get_serverlist returns error

### ISSUE THREAD

**Issue by stdcerr** [gotcha/vimpdb#17]
When my code hits `import vimpdb;vimpdb.set_trace()`, I get the following output:
```
File "/usr/local/lib/python2.7/dist-packages/vimpdb/config.py", line 251, in get_serverlist
    raise ValueError(RETURN_CODE % (command, return_code))
ValueError: 'vim --serverlist' returned exit code '1'.
```
and `vim --serverlist` gives me:
```
vim --serverlist
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 13 2020 16:04:38)
Unknown option argument: "--serverlist"
More info with: "vim -h"
```
What am I missing to get `vimpdb` up and running correctly in my environment?

**Comment by gotcha** [comment]
Did you check that your Vim supports clientserver ? Check the requirements section in the Readme.

**Comment by stdcerr** [comment]
That in fact was the issue, I'm on Ubuntu and needed to install `vim-gtk` instead to get `clientserver` support! Thank you
