### ISSUE TITLE
No module named 'StringIO'

### ISSUE THREAD

**Issue by bjce** [gotcha/vimpdb#19]
Hello. Many thanks for writing and maintaining vimpdb which I would very interested to inste. I just installed with pip and tried the following script (named `test3.py`:

```
from io import StringIO
import vimpdb
```

with: `vimpdb==0.4.5` and `Python 3.8.7`  on Macos 11.2.2

I get the followin error:
```
Traceback (most recent call last):
  File "test3.py", line 2, in <module>
    import vimpdb
  File "/Users/path_to/env/lib/python3.8/site-packages/vimpdb/__init__.py", line 1, in <module>
    from vimpdb.debugger import set_trace
  File "/Users/path_to/env/lib/python3.8/site-packages/vimpdb/debugger.py", line 4, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
```
What shall I do?

Many thanks in advance

**Comment by gotcha** [comment]
Unfortunately vimpdb does not support python 3 for now.

**Comment by bjce** [comment]
thanks for the quick answer @gotcha. Do you know any other alternative?

**Comment by gotcha** [comment]
I have not dug very recently. Last time I did, this was the only one.
